server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/web_tool?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

# mybatis配置  Mapper文件路径  输出日志
mybatis:
  mapper-locations: classpath:**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# mybatis的分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
